EdkRepo: Move sync specific strings to a sync specific location
tianocore/edk2-edkrepo pull request #138
Opened 2023-02-28 23:57 UTC by ashedesimone

Resolves #137

2023-03-14 19:05 UTC, kevinsun49 requested changes

2023-03-14 19:05 UTC, kevinsun49 commented on edkrepo/commands/sync_command.py
>              ui_functions.print_info_msg(SYNC_MANIFEST_UPDATE, header = False)
SYNC_MANIFEST_UPDATE

2023-03-14 19:06 UTC, kevinsun49 commented
Since all the sync-specific strings were moved out, do they all need to be prefixed with "SYNC_" in the sync humble file?

2023-03-14 21:19 UTC, ashedesimone commented
> Since all the sync-specific strings were moved out, do they still need to be prefixed with "SYNC_" in the sync humble file?

That is probably not a bad change I chose not to do it as part of this PR so that it would be easier to trace the change. Since only the location is changing not the definition.

2023-03-14 22:13 UTC, nate-desimone approved these changes

2023-03-15 01:24 UTC, kevinsun49 approved these changes

2023-03-15 01:25 UTC, kevinsun49 commented
> > Since all the sync-specific strings were moved out, do they still need to be prefixed with "SYNC_" in the sync humble file?
> 
> That is probably not a bad change I chose not to do it as part of this PR so that it would be easier to trace the change. Since only the location is changing not the definition.

Sounds good - we can address that in the future if we need to.

2023-03-15 23:30 UTC, merged