EdkRepo: Fix stack trace in List Pins
tianocore/edk2-edkrepo pull request #149
Opened 2023-03-17 00:58 UTC by ashedesimone

When use_less == true std_out was redirected to capture manifest parser output but never reset preventing subsequent print operations from being visible on the console.

Additionally switch from using subprocess.communitcate() to subprocess.run() to eliminate the stack trace reported in #148

Fixes #148

2023-03-21 20:34 UTC, nate-desimone requested changes

2023-03-21 20:34 UTC, nate-desimone commented on edkrepo/commands/list_pins_command.py
> +        sys.stdout = stdout
This needs to be put in the finally block of a try/finally to prevent an exception from causing this statement to not execute.

2023-03-21 20:34 UTC, nate-desimone commented on edkrepo/commands/list_pins_command.py
> +        print(less_path)
Remove debug prints

2023-04-11 00:14 UTC, kevinsun49 approved these changes

2023-04-12 21:56 UTC, nate-desimone approved these changes

2023-04-12 22:06 UTC, merged