Edkrepo: Add a path argument to Cache command
tianocore/edk2-edkrepo pull request #71
Opened 2022-06-09 00:56 UTC by hrsh25

Updated Cache command to accept an optional path argument
Signed-off-by: Harsh Vora harsh.vora@intel.com

2022-07-19 00:46 UTC, ashedesimone requested changes
In addition to the comments about the code your commit message must be updated to include a description of the change and include your signed off by.

2022-07-19 00:46 UTC, ashedesimone commented on edkrepo/commands/arguments/cache_args.py
> +COMMAND_PATH_HELP = 'Path for generating cache'
This should be 'Path where cache will be created' or similar

2022-07-19 22:45 UTC, ashedesimone commented
> Updated Cache command to accept an optional path argument Signed-off-by: Harsh Vora [harsh.vora@intel.com](mailto:harsh.vora@intel.com)

Hi Harsh, updating the comment on the conversation page will not update the commit message. You will need to update the commit message in your local branch using git commit --amend and then force push an update to your PR branch

2022-08-18 19:10 UTC, chrisyly requested changes
We can improve the behavior enabling cache path. Expected behavior:
- when cache is enabled, and path is being given when enabling cache, storing the path in the edkrepo config.
- If path is being defined in edkrepo config, set cache to use the user defined cache path instead of default path

2022-08-24 18:06 UTC, ashedesimone commented
> We can improve the behavior enabling cache path. Expected behavior:
> 
> * when cache is enabled, and path is being given when enabling cache, storing the path in the edkrepo config.
> * If path is being defined in edkrepo config, set cache to use the user defined cache path instead of default path

This is implemented in the most recent update to this PR

2022-08-24 22:50 UTC, kevinsun49 requested changes

2022-08-24 22:50 UTC, kevinsun49 commented on edkrepo/commands/cache_command.py
> +        #raise
Remove these commented out debug print statements

2022-08-25 08:57 UTC, chrisyly commented on edkrepo/commands/cache_command.py
> +        #raise
+1

2022-08-25 09:00 UTC, chrisyly approved these changes

2022-10-27 18:01 UTC, kevinsun49 approved these changes

2022-10-31 18:10 UTC, merged