EdkRepo: Update Error Codes in edkrepo_exception.py
tianocore/edk2-edkrepo pull request #96
Opened 2022-09-17 10:51 UTC by shree256

2022-09-17 11:40 UTC, shree256 commented
Hie @ashedesimone,
Made necessary changes in this branch as informed.
Was facing some issues over previous branch while fixing the required changes so created a new PR.

2022-09-18 09:16 UTC, shree256 commented
Hie @ashedesimone @nate-desimone,
Ran into some issue while fixing mentioned comments over #88, so created new one.
This contains fixes mentioned in #88.
Please review.

2022-09-20 19:05 UTC, ashedesimone requested changes
Thanks for the updates they look good.

I see that there are now 2 commits on this PR branch. Please remove the second commit.

2022-09-20 19:06 UTC, ashedesimone commented
If you need assistance with updating the PR branch I can help please let me know. I will need push access to the branch on your fork in that case.

2022-09-21 08:35 UTC, shree256 commented
Please assist me.
Have sent you invite for the same.

2022-09-21 18:51 UTC, ashedesimone commented
> Please assist me. Have sent you invite for the access. Thanks.

Hi I rebased the branch you are sending your PR from to be up to date with main, removed the merge commit and placed the commit with your change on top.

2022-09-21 18:51 UTC, ashedesimone approved these changes

2022-09-21 18:51 UTC, merged

2022-09-21 19:16 UTC, shree256 commented
Got it. Thanks for update.